# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'MainMenuWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json
import settings


class MainMenuWidget(QtWidgets.QWidget):
    def __init__(self, *args, **kwargs):
        super(MainMenuWidget, self).__init__(*args, **kwargs)
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_29 = QtWidgets.QFrame(self)
        self.frame_29.setStyleSheet("")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_3 = QtWidgets.QFrame(self.frame_29)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_3.setFont(font)
        self.setStyleSheet("QFrame{\n"
"   background-color: rgba(255, 255, 255, 0);\n"
"}\n")
        self.frame_3.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #DCDCDC;\n"
"}\n"
"QComboBox\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    padding-left: 20px;\n"
"    combobox-popup: 0;\n"
"}\n"
"\n"
"QComboBox::drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: white;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 10px;"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.scripts_map = QtWidgets.QComboBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scripts_map.sizePolicy().hasHeightForWidth())
        self.scripts_map.setSizePolicy(sizePolicy)
        self.scripts_map.setMinimumSize(QtCore.QSize(0, 40))
        self.scripts_map.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.scripts_map.setFont(font)
        self.scripts_map.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scripts_map.view().setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scripts_map.setObjectName("scripts_map")
        self.verticalLayout_4.addWidget(self.scripts_map)
        self.verticalLayout.addWidget(self.frame_5)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.script1_box = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.script1_box.sizePolicy().hasHeightForWidth())
        self.script1_box.setSizePolicy(sizePolicy)
        self.script1_box.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.script1_box.setFont(font)
        self.script1_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.script1_box.view().setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.script1_box.setObjectName("script1_box")
        self.verticalLayout_3.addWidget(self.script1_box)
        self.script2_box = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.script2_box.sizePolicy().hasHeightForWidth())
        self.script2_box.setSizePolicy(sizePolicy)
        self.script2_box.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.script2_box.setFont(font)
        self.script2_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.script2_box.setStyleSheet("")
        self.script2_box.view().setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.script2_box.setObjectName("script2_box")
        self.verticalLayout_3.addWidget(self.script2_box)
        self.script3_box = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.script3_box.sizePolicy().hasHeightForWidth())
        self.script3_box.setSizePolicy(sizePolicy)
        self.script3_box.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.script3_box.setFont(font)
        self.script3_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.script3_box.setStyleSheet("")
        self.script3_box.view().setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.script3_box.setObjectName("script3_box")
        self.verticalLayout_3.addWidget(self.script3_box)
        self.script4_box = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.script4_box.sizePolicy().hasHeightForWidth())
        self.script4_box.setSizePolicy(sizePolicy)
        self.script4_box.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.script4_box.setFont(font)
        self.script4_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.script4_box.setStyleSheet("")
        self.script4_box.view().setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.script4_box.setObjectName("script4_box")
        self.verticalLayout_3.addWidget(self.script4_box)
        self.script5_box = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.script5_box.sizePolicy().hasHeightForWidth())
        self.script5_box.setSizePolicy(sizePolicy)
        self.script5_box.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.script5_box.setFont(font)
        self.script5_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.script5_box.setStyleSheet("")
        self.script5_box.view().setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.script5_box.setObjectName("script5_box")
        self.verticalLayout_3.addWidget(self.script5_box)
        self.verticalLayout.addWidget(self.widget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.help_label = QtWidgets.QLabel(self.frame_6)
        self.help_label.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.help_label.setFont(font)
        self.help_label.setStyleSheet("QLabel{\n"
"background-color:#90EE90;\n"
"border-style: dashed;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"color: black;\n"
"}")
        self.help_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.help_label.setIndent(-1)
        self.help_label.setWordWrap(True)
        self.help_label.setObjectName("help_label")
        self.gridLayout_3.addWidget(self.help_label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem2)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_2.setSpacing(0)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setContentsMargins(50, -1, 50, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.emergency_lighting_button = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emergency_lighting_button.sizePolicy().hasHeightForWidth())
        self.emergency_lighting_button.setSizePolicy(sizePolicy)
        self.emergency_lighting_button.setMinimumSize(QtCore.QSize(100, 50))
        self.emergency_lighting_button.setMaximumSize(QtCore.QSize(200, 140))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.emergency_lighting_button.setFont(font)
        self.emergency_lighting_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.emergency_lighting_button.setAutoFillBackground(False)
        self.emergency_lighting_button.setStyleSheet("")
        self.emergency_lighting_button.setObjectName("emergency_lighting_button")
        self.gridLayout_4.addWidget(self.emergency_lighting_button, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout_16.addWidget(self.frame_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.frame_8 = QtWidgets.QFrame(self.frame_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setStyleSheet("QSpinBox\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"}\n"
"QSpinBox::up-button { width: 0px; }\n"
"QSpinBox::down-button { width: 0px; }\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #DCDCDC;\n"
"}\n"
"QComboBox\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    padding-left: 20px;\n"
"    combobox-popup: 0;\n"
"}\n"
"\n"
"QComboBox::drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: white;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 10px;"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_2 = QtWidgets.QWidget(self.frame_8)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.participants_box = QtWidgets.QSpinBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.participants_box.sizePolicy().hasHeightForWidth())
        self.participants_box.setSizePolicy(sizePolicy)
        self.participants_box.setMaximumSize(QtCore.QSize(100, 80))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.participants_box.setFont(font)
        self.participants_box.setStyleSheet("")
        self.participants_box.setAlignment(QtCore.Qt.AlignCenter)
        self.participants_box.setMinimum(1)
        self.participants_box.setProperty("value", 1)
        self.participants_box.setObjectName("participants_box")
        self.horizontalLayout_2.addWidget(self.participants_box)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.widget_2)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.celebrant_box = QtWidgets.QComboBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.celebrant_box.sizePolicy().hasHeightForWidth())
        self.celebrant_box.setSizePolicy(sizePolicy)
        self.celebrant_box.setMinimumSize(QtCore.QSize(0, 50))
        self.celebrant_box.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.celebrant_box.setFont(font)
        self.celebrant_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.celebrant_box.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.celebrant_box.view().setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.celebrant_box.setObjectName("celebrant_box")
        self.celebrant_box.addItem("")
        self.celebrant_box.addItem("")
        self.verticalLayout_8.addWidget(self.celebrant_box)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.instructors_box = QtWidgets.QTextEdit(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instructors_box.sizePolicy().hasHeightForWidth())
        self.instructors_box.setSizePolicy(sizePolicy)
        self.instructors_box.setMinimumSize(QtCore.QSize(0, 50))
        self.instructors_box.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.instructors_box.setFont(font)
        self.instructors_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.instructors_box.setStyleSheet("QTextEdit\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    padding: 25px;\n"
"}")
        self.instructors_box.setObjectName("instructors_box")
        self.verticalLayout_9.addWidget(self.instructors_box)
        self.verticalLayout_7.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.volume_level = QtWidgets.QSlider(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volume_level.sizePolicy().hasHeightForWidth())
        self.volume_level.setSizePolicy(sizePolicy)
        self.volume_level.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.volume_level.setStyleSheet("QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: white;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 rgba(4,38,14,255), stop: 1 rgba(5, 169, 83, 255));\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.volume_level.setProperty("value", 100)
        self.volume_level.setOrientation(QtCore.Qt.Horizontal)
        self.volume_level.setObjectName("volume_level")
        self.verticalLayout_10.addWidget(self.volume_level)
        self.verticalLayout_7.addWidget(self.frame_11)
        self.horizontalLayout_16.addWidget(self.frame_8)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.frame = QtWidgets.QFrame(self.frame_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #DCDCDC;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: white;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding-left: 15px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 30px;\n"
"    height: 30px;\n"
"    background-color: gray;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: white white black black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: qradialgradient(spread:pad, \n"
"                            cx:0.5,\n"
"                            cy:0.5,\n"
"                            radius:0.9,\n"
"                            fx:0.5,\n"
"                            fy:0.5,\n"
"                            stop:0 rgba(0, 255, 0, 255), \n"
"                            stop:1 rgba(0, 64, 0, 255));\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: qradialgradient(spread:pad, \n"
"                            cx:0.5,\n"
"                            cy:0.5,\n"
"                            radius:0.9,\n"
"                            fx:0.5,\n"
"                            fy:0.5,\n"
"                            stop:0 rgba(255, 0, 0, 255), \n"
"                            stop:1 rgba(64, 0, 0, 255));\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_12 = QtWidgets.QFrame(self.frame)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.start_game_button = QtWidgets.QPushButton(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_game_button.sizePolicy().hasHeightForWidth())
        self.start_game_button.setSizePolicy(sizePolicy)
        self.start_game_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.start_game_button.setFont(font)
        self.start_game_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_game_button.setStyleSheet("")
        self.start_game_button.setObjectName("start_game_button")
        self.horizontalLayout_3.addWidget(self.start_game_button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.stop_game_button = QtWidgets.QPushButton(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_game_button.sizePolicy().hasHeightForWidth())
        self.stop_game_button.setSizePolicy(sizePolicy)
        self.stop_game_button.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.stop_game_button.setFont(font)
        self.stop_game_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_game_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #ff0000;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #bb0000;\n"
"}")
        self.stop_game_button.setObjectName("stop_game_button")
        self.horizontalLayout_3.addWidget(self.stop_game_button)
        self.verticalLayout_11.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setStyleSheet("")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.check_game_time = QtWidgets.QCheckBox(self.frame_13)
        self.check_game_time.setCheckState(2)
        self.check_game_time.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.check_game_time.setFont(font)
        self.check_game_time.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_game_time.setStyleSheet("")
        self.check_game_time.setObjectName("check_game_time")
        self.verticalLayout_12.addWidget(self.check_game_time)
        self.main_timer = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.main_timer.setFont(font)
        self.main_timer.setStyleSheet("QLabel\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    color: #000000;\n"
"}")
        self.main_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.main_timer.setObjectName("main_timer")
        self.verticalLayout_12.addWidget(self.main_timer)
        self.frame_16 = QtWidgets.QFrame(self.frame_13)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.reduce_time_button = QtWidgets.QPushButton(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reduce_time_button.sizePolicy().hasHeightForWidth())
        self.reduce_time_button.setSizePolicy(sizePolicy)
        self.reduce_time_button.setMinimumSize(QtCore.QSize(50, 20))
        self.reduce_time_button.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.reduce_time_button.setFont(font)
        self.reduce_time_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reduce_time_button.setStyleSheet("")
        self.reduce_time_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reduce_time_button.setIcon(icon)
        self.reduce_time_button.setObjectName("reduce_time_button")
        self.horizontalLayout_4.addWidget(self.reduce_time_button)
        self.add_time_button = QtWidgets.QPushButton(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_time_button.sizePolicy().hasHeightForWidth())
        self.add_time_button.setSizePolicy(sizePolicy)
        self.add_time_button.setMinimumSize(QtCore.QSize(50, 20))
        self.add_time_button.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_time_button.setFont(font)
        self.add_time_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_time_button.setStyleSheet("")
        self.add_time_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_time_button.setIcon(icon1)
        self.add_time_button.setObjectName("add_time_button")
        self.horizontalLayout_4.addWidget(self.add_time_button)
        self.label_11 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.verticalLayout_12.addWidget(self.frame_16)
        self.verticalLayout_11.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.check_game_score = QtWidgets.QCheckBox(self.frame_14)
        self.check_game_score.setMinimumSize(QtCore.QSize(0, 50))
        self.check_game_score.setCheckState(2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.check_game_score.setFont(font)
        self.check_game_score.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_game_score.setStyleSheet("")
        self.check_game_score.setObjectName("check_game_score")
        self.verticalLayout_13.addWidget(self.check_game_score)
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.red_count_label = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.red_count_label.setFont(font)
        self.red_count_label.setStyleSheet("QLabel\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    color: #000000;\n"
"}")
        self.red_count_label.setAlignment(QtCore.Qt.AlignCenter)
        self.red_count_label.setObjectName("red_count_label")
        self.verticalLayout_15.addWidget(self.red_count_label)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.down_red_button = QtWidgets.QPushButton(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.down_red_button.sizePolicy().hasHeightForWidth())
        self.down_red_button.setSizePolicy(sizePolicy)
        self.down_red_button.setMinimumSize(QtCore.QSize(50, 20))
        self.down_red_button.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.down_red_button.setFont(font)
        self.down_red_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.down_red_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.down_red_button.setStyleSheet("")
        self.down_red_button.setText("")
        self.down_red_button.setIcon(icon)
        self.down_red_button.setObjectName("down_red_button")
        self.horizontalLayout_6.addWidget(self.down_red_button)
        self.up_red_button = QtWidgets.QPushButton(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_red_button.sizePolicy().hasHeightForWidth())
        self.up_red_button.setSizePolicy(sizePolicy)
        self.up_red_button.setMinimumSize(QtCore.QSize(50, 20))
        self.up_red_button.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.up_red_button.setFont(font)
        self.up_red_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.up_red_button.setStyleSheet("")
        self.up_red_button.setText("")
        self.up_red_button.setIcon(icon1)
        self.up_red_button.setObjectName("up_red_button")
        self.horizontalLayout_6.addWidget(self.up_red_button)
        self.verticalLayout_15.addWidget(self.frame_19)
        self.horizontalLayout_5.addWidget(self.frame_17)
        spacerItem6 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.frame_18 = QtWidgets.QFrame(self.frame_15)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_14.addWidget(self.label_13)
        self.blue_count_label = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.blue_count_label.setFont(font)
        self.blue_count_label.setStyleSheet("QLabel\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #0000bb;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    color: #000000;\n"
"}")
        self.blue_count_label.setAlignment(QtCore.Qt.AlignCenter)
        self.blue_count_label.setObjectName("blue_count_label")
        self.verticalLayout_14.addWidget(self.blue_count_label)
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.down_blue_button = QtWidgets.QPushButton(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.down_blue_button.sizePolicy().hasHeightForWidth())
        self.down_blue_button.setSizePolicy(sizePolicy)
        self.down_blue_button.setMinimumSize(QtCore.QSize(50, 20))
        self.down_blue_button.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.down_blue_button.setFont(font)
        self.down_blue_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.down_blue_button.setStyleSheet("")
        self.down_blue_button.setText("")
        self.down_blue_button.setIcon(icon)
        self.down_blue_button.setObjectName("down_blue_button")
        self.horizontalLayout_7.addWidget(self.down_blue_button)
        self.up_blue_button = QtWidgets.QPushButton(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_blue_button.sizePolicy().hasHeightForWidth())
        self.up_blue_button.setSizePolicy(sizePolicy)
        self.up_blue_button.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.up_blue_button.setFont(font)
        self.up_blue_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.up_blue_button.setStyleSheet("")
        self.up_blue_button.setText("")
        self.up_blue_button.setIcon(icon1)
        self.up_blue_button.setObjectName("up_blue_button")
        self.horizontalLayout_7.addWidget(self.up_blue_button)
        self.verticalLayout_14.addWidget(self.frame_20)
        self.horizontalLayout_5.addWidget(self.frame_18)
        self.verticalLayout_13.addWidget(self.frame_15)
        self.verticalLayout_11.addWidget(self.frame_14)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem7)
        self.horizontalLayout_16.addWidget(self.frame)
        self.gridLayout.addWidget(self.frame_29, 0, 0, 1, 1)

        self.read_json()
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self.disabled_scripts()

    def read_json(self):
        with open('data.txt') as json_file:
            self.data = json.load(json_file)

    def set_script_boxes(self, translate):
        for scr in self.data['scripts']:
            self.script1_box.addItem(translate("self", scr['script']))
            self.script2_box.addItem(translate("self", scr['script']))
            self.script3_box.addItem(translate("self", scr['script']))
            self.script4_box.addItem(translate("self", scr['script']))
            self.script5_box.addItem(translate("self", scr['script']))

    def set_scripts_map(self, translate):
        for scr in self.data['scripts_map']:
            self.scripts_map.addItem(translate("self", scr['name']))

    def yellow_start_button(self):
        self.start_game_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #ffff00;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #bbbb00;\n"
"}")
    def white_start_button(self):
        self.start_game_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #ffffff;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #DCDCDC;\n"
"}")
    def green_start_button(self):
        self.start_game_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #00ff00;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #00bb00;\n"
"}")

    def change_participants_box(self):
        if self.participants_box.value() < 6:
            self.participants_box.setStyleSheet(
                "QSpinBox\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"}\n"
"QSpinBox::up-button { width: 0px; }\n"
"QSpinBox::down-button { width: 0px; }\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
            )
        else:
            self.participants_box.setStyleSheet(
                "QSpinBox\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #00bb00;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"}\n"
"QSpinBox::up-button { width: 0px; }\n"
"QSpinBox::down-button { width: 0px; }\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
            )

    def change_celebrant_box(self):
        if self.celebrant_box.currentIndex() == 0:
            self.celebrant_box.setStyleSheet("QComboBox\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    padding-left: 20px;\n"
"    combobox-popup: 0;\n"
"}\n"
"\n"
"QComboBox::drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}\n")
        else:
            self.celebrant_box.setStyleSheet("QComboBox\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #00bb00;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    padding-left: 20px;\n"
"    combobox-popup: 0;\n"
"}\n"
"\n"
"QComboBox::drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}\n")

    def change_instructors_box(self):
        if self.instructors_box.toPlainText() == '':
            self.instructors_box.setStyleSheet("QTextEdit\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    padding: 25px;\n"
"}")
        else:
            self.instructors_box.setStyleSheet("QTextEdit\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #00bb00;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    padding: 25px;\n"
"}")

    def change_script_box(self, script_box):
        if script_box.currentText() == 'Сценарий не выбран':
            script_box.setStyleSheet("QComboBox\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    padding-left: 20px;\n"
"    combobox-popup: 0;\n"
"}\n"
"\n"
"QComboBox::drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}\n")
        else:
            script_box.setStyleSheet("QComboBox\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #00bb00;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    padding-left: 20px;\n"
"    combobox-popup: 0;\n"
"}\n"
"\n"
"QComboBox::drop-down \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  color: rgb(85, 170, 255);    \n"
"  background-color: #373e4e;\n"
"  padding: 10px;\n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}\n")

    def disabled_scripts_map(self):
        self.scripts_map.setDisabled(True)

    def enabled_scripts_map(self):
        self.scripts_map.setDisabled(False)

    def disabled_script(self, number):
        if number == 1:
            self.script1_box.setDisabled(True)
        elif number == 2:
            self.script2_box.setDisabled(True)
        elif number == 3:
            self.script3_box.setDisabled(True)
        elif number == 4:
            self.script4_box.setDisabled(True)
        elif number == 5:
            self.script5_box.setDisabled(True)

    def set_scripts_text(self, script_box, text):
        script_box.setCurrentText(text)
        if text == 'Сценарий не выбран':
            script_box.setDisabled(True)

    def disabled_script1(self):
        self.script1_box.setDisabled(True)
    def disabled_script2(self):
        self.script2_box.setDisabled(True)
    def disabled_script3(self):
        self.script3_box.setDisabled(True)
    def disabled_script4(self):
        self.script4_box.setDisabled(True)
    def disabled_script5(self):
        self.script5_box.setDisabled(True)

    def disabled_scripts(self):
        self.script1_box.setDisabled(True)
        self.script2_box.setDisabled(True)
        self.script3_box.setDisabled(True)
        self.script4_box.setDisabled(True)
        self.script5_box.setDisabled(True)

    def enabled_scripts(self):
        self.script1_box.setDisabled(False)
        self.script2_box.setDisabled(False)
        self.script3_box.setDisabled(False)
        self.script4_box.setDisabled(False)
        self.script5_box.setDisabled(False)

    def disabled_check_time(self):
        self.check_game_time.setDisabled(True)

    def enabled_check_time(self):
        self.check_game_time.setDisabled(False)

    def disabled_updown_buttons(self):
        self.up_red_button.setDisabled(True)
        self.up_blue_button.setDisabled(True)
        self.down_red_button.setDisabled(True)
        self.down_blue_button.setDisabled(True)

    def enabled_updown_buttons(self):
        self.up_red_button.setDisabled(False)
        self.up_blue_button.setDisabled(False)
        self.down_red_button.setDisabled(False)
        self.down_blue_button.setDisabled(False)

    def green_timer(self):
        self.main_timer.setStyleSheet("QLabel\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #00bb00;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    color: #000000;\n"
"}")

    def red_timer(self):
        self.main_timer.setStyleSheet("QLabel\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    color: #000000;\n"
"}")

    def set_time(self, text):
        self.main_timer.setText(text)

    def stop_game_button_press(self):
        pass

    def emergency_button_on(self):
        self.emergency_lighting_button.setText('On')
    def emergency_button_off(self):
        self.emergency_lighting_button.setText('Off')

    def emergency_button_press(self):
        settings.emergencyEvent = True

    def add_time(self):
        settings.mainTime+=60
        settings.addedTime+=60
        self.set_main_time()
    def reduce_time(self):
        if settings.addedTime and settings.mainTime-60 > 0:
            settings.mainTime-=60
            settings.addedTime-=60
            self.set_main_time()
    def set_main_time(self):
        self.main_timer.setText(
            f"{settings.get_hours(settings.mainTime)} :" +\
            f" {settings.get_minutes(settings.mainTime)} :" +\
            f" {settings.get_seconds(settings.mainTime)}")

    def reset_counters(self):
        self.red_count_label.setText('0')
        self.blue_count_label.setText('0')

    def add_main_score_red(self):
        settings.counters['mainСounterRed']+=1
        self.red_count_label.setText(str(settings.counters['mainСounterRed']))
    def add_main_score_blue(self):
        settings.counters['mainСounterBlue']+=1
        self.blue_count_label.setText(str(settings.counters['mainСounterBlue']))
    def reduce_main_score_red(self):
        if settings.counters['mainСounterRed']:
            settings.counters['mainСounterRed']-=1
            self.red_count_label.setText(str(settings.counters['mainСounterRed']))
    def reduce_main_score_blue(self):
        if settings.counters['mainСounterBlue']:
            settings.counters['mainСounterBlue']-=1
            self.blue_count_label.setText(str(settings.counters['mainСounterBlue']))

    def change_help(self, text):
        self.help_label.setText(f'Подсказка: {text}')

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.label.setText(_translate("self", "Сценарная карта:"))
        self.set_scripts_map(_translate)
        self.label_4.setText(_translate("self", "Игровые сценарии:"))
        self.set_script_boxes(_translate)
        self.help_label.setText(_translate("self", "Подсказка:"))
        self.label_3.setText(_translate("self", "Аварийное включение\n"
"освещения"))
        self.emergency_lighting_button.setText(_translate("self", "ON"))
        self.label_6.setText(_translate("self", "Количество\n"
"участников"))
        self.label_7.setText(_translate("self", "Имя именинника"))
        self.celebrant_box.setItemText(0, _translate("self", "Именинник не выбран"))
        self.celebrant_box.setItemText(1, _translate("self", "Нет именинника"))
        self.label_8.setText(_translate("self", "Инструкторы"))
        self.label_5.setText(_translate("self", "Регулятор громкости"))
        self.start_game_button.setText(_translate("self", "Запуск игры"))
        self.stop_game_button.setText(_translate("self", "Стоп"))
        self.check_game_time.setText(_translate("self", "Время игры"))
        self.main_timer.setText(_translate("self", "01 : 29 : 00"))
        self.label_10.setText(_translate("self", "-1 мин"))
        self.label_11.setText(_translate("self", "+1 мин"))
        self.check_game_score.setText(_translate("self", "Счет игры"))
        self.label_12.setText(_translate("self", "Красные"))
        self.red_count_label.setText(_translate("self", "0"))
        self.label_13.setText(_translate("self", "Синие"))
        self.blue_count_label.setText(_translate("self", "0"))
