# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NotScriptWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import settings
from scriptWidget import ScriptWidget


class NoScriptWidget(ScriptWidget):
    def __init__(self, *args, **kwargs):
        super(NoScriptWidget, self).__init__(*args, **kwargs)
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self)
        self.setStyleSheet("QFrame{\n"
"   background-color: rgba(255, 255, 255, 0);\n"
"}\n")
        self.widget_3.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #DCDCDC;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_21 = QtWidgets.QFrame(self.widget_3)
        self.frame_21.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(0,0,0,0);\n"
"    padding: 10px;"
"}\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #DCDCDC;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: white;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 30px;\n"
"    height: 30px;\n"
"    background-color: gray;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: white white black black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: qradialgradient(spread:pad, \n"
"                            cx:0.5,\n"
"                            cy:0.5,\n"
"                            radius:0.9,\n"
"                            fx:0.5,\n"
"                            fy:0.5,\n"
"                            stop:0 rgba(0, 255, 0, 255), \n"
"                            stop:1 rgba(0, 64, 0, 255));\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: qradialgradient(spread:pad, \n"
"                            cx:0.5,\n"
"                            cy:0.5,\n"
"                            radius:0.9,\n"
"                            fx:0.5,\n"
"                            fy:0.5,\n"
"                            stop:0 rgba(255, 0, 0, 255), \n"
"                            stop:1 rgba(64, 0, 0, 255));\n"
"}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.stage_label1 = QtWidgets.QLabel(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage_label1.sizePolicy().hasHeightForWidth())
        self.stage_label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.stage_label1.setFont(font)
        self.stage_label1.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: white;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}")
        self.stage_label1.setAlignment(QtCore.Qt.AlignCenter)
        self.stage_label1.setObjectName("stage_label1")
        self.horizontalLayout.addWidget(self.stage_label1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_16.addLayout(self.horizontalLayout)
        self.frame_23 = QtWidgets.QFrame(self.frame_21)
        self.frame_23.setStyleSheet("QFrame{\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.exclude_stage1 = QtWidgets.QCheckBox(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.exclude_stage1.setFont(font)
        self.exclude_stage1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exclude_stage1.setStyleSheet("")
        self.exclude_stage1.setObjectName("exclude_stage1")
        self.horizontalLayout_9.addWidget(self.exclude_stage1)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.wow_effects1 = QtWidgets.QCheckBox(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.wow_effects1.setFont(font)
        self.wow_effects1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wow_effects1.setStyleSheet("")
        self.wow_effects1.setObjectName("wow_effects1")
        self.horizontalLayout_9.addWidget(self.wow_effects1)
        self.verticalLayout_16.addWidget(self.frame_23)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_16.addItem(spacerItem3)
        self.frame_24 = QtWidgets.QFrame(self.frame_21)
        self.frame_24.setStyleSheet("QFrame{\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.start_stage1_button = QtWidgets.QPushButton(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_stage1_button.sizePolicy().hasHeightForWidth())
        self.start_stage1_button.setSizePolicy(sizePolicy)
        self.start_stage1_button.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.start_stage1_button.setFont(font)
        self.start_stage1_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_stage1_button.setStyleSheet("")
        self.start_stage1_button.setObjectName("start_stage1_button")
        self.horizontalLayout_10.addWidget(self.start_stage1_button)
        spacerItem5 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.stop_stage1_button = QtWidgets.QPushButton(self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_stage1_button.sizePolicy().hasHeightForWidth())
        self.stop_stage1_button.setSizePolicy(sizePolicy)
        self.stop_stage1_button.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.stop_stage1_button.setFont(font)
        self.stop_stage1_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_stage1_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #ff0000;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #bb0000;\n"
"}")
        self.stop_stage1_button.setObjectName("stop_stage1_button")
        self.horizontalLayout_10.addWidget(self.stop_stage1_button)
        spacerItem6 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.verticalLayout_16.addWidget(self.frame_24)
        self.horizontalLayout_restart1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_restart1.setObjectName("horizontalLayout_restart1")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_restart1.addItem(spacerItem7)
        self.result_stage1_widget = QtWidgets.QLabel(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_stage1_widget.sizePolicy().hasHeightForWidth())
        self.result_stage1_widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.result_stage1_widget.setFont(font)
        self.result_stage1_widget.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: white;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}")
        self.result_stage1_widget.setAlignment(QtCore.Qt.AlignCenter)
        self.result_stage1_widget.setObjectName("result_stage1_widget")
        self.horizontalLayout_restart1.addWidget(self.result_stage1_widget)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_restart1.addItem(spacerItem8)
        self.verticalLayout_16.addLayout(self.horizontalLayout_restart1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem9)
        self.label_20 = QtWidgets.QLabel(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: white;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}")
        self.label_20.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_16.addWidget(self.label_20)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem10)
        self.check_stage1_time = QtWidgets.QCheckBox(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_stage1_time.sizePolicy().hasHeightForWidth())
        self.check_stage1_time.setSizePolicy(sizePolicy)
        self.check_stage1_time.setMinimumSize(QtCore.QSize(0, 0))
        self.check_stage1_time.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.check_stage1_time.setFont(font)
        self.check_stage1_time.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_stage1_time.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.check_stage1_time.setObjectName("check_stage1_time")
        self.horizontalLayout_17.addWidget(self.check_stage1_time)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.verticalLayout_16.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem12)
        self.stage1_timer = QtWidgets.QLabel(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage1_timer.sizePolicy().hasHeightForWidth())
        self.stage1_timer.setSizePolicy(sizePolicy)
        self.stage1_timer.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.stage1_timer.setFont(font)
        self.stage1_timer.setStyleSheet("QLabel\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    color: #000000;\n"
"}")
        self.stage1_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.stage1_timer.setObjectName("stage1_timer")
        self.horizontalLayout_18.addWidget(self.stage1_timer)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem13)
        self.verticalLayout_16.addLayout(self.horizontalLayout_18)
        self.frame_26 = QtWidgets.QFrame(self.frame_21)
        self.frame_26.setStyleSheet("QFrame{\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_22 = QtWidgets.QLabel(self.frame_26)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        self.reduce_time_bt1 = QtWidgets.QPushButton(self.frame_26)
        self.reduce_time_bt1.setMinimumSize(QtCore.QSize(0, 30))
        self.reduce_time_bt1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.reduce_time_bt1.setFont(font)
        self.reduce_time_bt1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reduce_time_bt1.setStyleSheet("")
        self.reduce_time_bt1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reduce_time_bt1.setIcon(icon)
        self.reduce_time_bt1.setObjectName("reduce_time_bt1")
        self.horizontalLayout_11.addWidget(self.reduce_time_bt1)
        self.add_time_bt1 = QtWidgets.QPushButton(self.frame_26)
        self.add_time_bt1.setMinimumSize(QtCore.QSize(0, 30))
        self.add_time_bt1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.add_time_bt1.setFont(font)
        self.add_time_bt1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_time_bt1.setStyleSheet("")
        self.add_time_bt1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_time_bt1.setIcon(icon1)
        self.add_time_bt1.setObjectName("add_time_bt1")
        self.horizontalLayout_11.addWidget(self.add_time_bt1)
        self.label_23 = QtWidgets.QLabel(self.frame_26)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_11.addWidget(self.label_23)
        self.verticalLayout_16.addWidget(self.frame_26)
        self.horizontalLayout_8.addWidget(self.frame_21)
        self.line = QtWidgets.QFrame(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.line.setFont(font)
        self.line.setAutoFillBackground(False)
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_8.addWidget(self.line)
        self.line_2 = QtWidgets.QFrame(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.line_2.setFont(font)
        self.line_2.setAutoFillBackground(False)
        self.line_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_8.addWidget(self.line_2)
        self.frame_22 = QtWidgets.QFrame(self.widget_3)
        self.frame_22.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(0,0,0,0);\n"
"    padding: 10px;"
"}\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #DCDCDC;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: white;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 30px;\n"
"    height: 30px;\n"
"    background-color: gray;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: white white black black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: qradialgradient(spread:pad, \n"
"                            cx:0.5,\n"
"                            cy:0.5,\n"
"                            radius:0.9,\n"
"                            fx:0.5,\n"
"                            fy:0.5,\n"
"                            stop:0 rgba(0, 255, 0, 255), \n"
"                            stop:1 rgba(0, 64, 0, 255));\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: qradialgradient(spread:pad, \n"
"                            cx:0.5,\n"
"                            cy:0.5,\n"
"                            radius:0.9,\n"
"                            fx:0.5,\n"
"                            fy:0.5,\n"
"                            stop:0 rgba(255, 0, 0, 255), \n"
"                            stop:1 rgba(64, 0, 0, 255));\n"
"}")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem14)
        self.stage_label2 = QtWidgets.QLabel(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage_label2.sizePolicy().hasHeightForWidth())
        self.stage_label2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.stage_label2.setFont(font)
        self.stage_label2.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: white;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}")
        self.stage_label2.setAlignment(QtCore.Qt.AlignCenter)
        self.stage_label2.setObjectName("stage_label2")
        self.horizontalLayout_12.addWidget(self.stage_label2)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem15)
        self.verticalLayout_17.addLayout(self.horizontalLayout_12)
        self.frame_25 = QtWidgets.QFrame(self.frame_22)
        self.frame_25.setStyleSheet("QFrame{\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.exclude_stage2 = QtWidgets.QCheckBox(self.frame_25)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.exclude_stage2.setFont(font)
        self.exclude_stage2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exclude_stage2.setStyleSheet("")
        self.exclude_stage2.setObjectName("exclude_stage2")
        self.horizontalLayout_13.addWidget(self.exclude_stage2)
        spacerItem16 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem16)
        self.wow_effects2 = QtWidgets.QCheckBox(self.frame_25)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.wow_effects2.setFont(font)
        self.wow_effects2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wow_effects2.setStyleSheet("")
        self.wow_effects2.setObjectName("wow_effects2")
        self.horizontalLayout_13.addWidget(self.wow_effects2)
        self.verticalLayout_17.addWidget(self.frame_25)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_17.addItem(spacerItem17)
        self.frame_27 = QtWidgets.QFrame(self.frame_22)
        self.frame_27.setStyleSheet("QFrame{\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem18 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem18)
        self.start_stage2_button = QtWidgets.QPushButton(self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_stage2_button.sizePolicy().hasHeightForWidth())
        self.start_stage2_button.setSizePolicy(sizePolicy)
        self.start_stage2_button.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.start_stage2_button.setFont(font)
        self.start_stage2_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_stage2_button.setStyleSheet("")
        self.start_stage2_button.setObjectName("start_stage2_button")
        self.horizontalLayout_14.addWidget(self.start_stage2_button)
        spacerItem19 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem19)
        self.stop_stage2_button = QtWidgets.QPushButton(self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_stage2_button.sizePolicy().hasHeightForWidth())
        self.stop_stage2_button.setSizePolicy(sizePolicy)
        self.stop_stage2_button.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.stop_stage2_button.setFont(font)
        self.stop_stage2_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_stage2_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #ff0000;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #bb0000;\n"
"}")
        self.stop_stage2_button.setObjectName("stop_stage2_button")
        self.horizontalLayout_14.addWidget(self.stop_stage2_button)
        spacerItem20 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem20)
        self.verticalLayout_17.addWidget(self.frame_27)
        self.horizontalLayout_restart2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_restart2.setObjectName("horizontalLayout_restart2")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_restart2.addItem(spacerItem21)
        self.result_stage2_widget = QtWidgets.QLabel(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_stage2_widget.sizePolicy().hasHeightForWidth())
        self.result_stage2_widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.result_stage2_widget.setFont(font)
        self.result_stage2_widget.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: white;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}")
        self.result_stage2_widget.setAlignment(QtCore.Qt.AlignCenter)
        self.result_stage2_widget.setObjectName("result_stage2_widget")
        self.horizontalLayout_restart2.addWidget(self.result_stage2_widget)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_restart2.addItem(spacerItem22)
        self.verticalLayout_17.addLayout(self.horizontalLayout_restart2)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem23)
        self.label_24 = QtWidgets.QLabel(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: white;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}")
        self.label_24.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_17.addWidget(self.label_24)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem24)
        self.check_stage2_time = QtWidgets.QCheckBox(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_stage2_time.sizePolicy().hasHeightForWidth())
        self.check_stage2_time.setSizePolicy(sizePolicy)
        self.check_stage2_time.setMinimumSize(QtCore.QSize(0, 0))
        self.check_stage2_time.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.check_stage2_time.setFont(font)
        self.check_stage2_time.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_stage2_time.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.check_stage2_time.setObjectName("check_stage2_time")
        self.horizontalLayout_19.addWidget(self.check_stage2_time)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem25)
        self.verticalLayout_17.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem26)
        self.stage2_timer = QtWidgets.QLabel(self.frame_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage2_timer.sizePolicy().hasHeightForWidth())
        self.stage2_timer.setSizePolicy(sizePolicy)
        self.stage2_timer.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.stage2_timer.setFont(font)
        self.stage2_timer.setStyleSheet("QLabel\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    color: #000000;\n"
"}")
        self.stage2_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.stage2_timer.setObjectName("stage2_timer")
        self.horizontalLayout_20.addWidget(self.stage2_timer)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem27)
        self.verticalLayout_17.addLayout(self.horizontalLayout_20)
        self.frame_28 = QtWidgets.QFrame(self.frame_22)
        self.frame_28.setStyleSheet("QFrame{\n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_26 = QtWidgets.QLabel(self.frame_28)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_21.addWidget(self.label_26)
        self.reduce_time_bt2 = QtWidgets.QPushButton(self.frame_28)
        self.reduce_time_bt2.setMinimumSize(QtCore.QSize(0, 30))
        self.reduce_time_bt2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.reduce_time_bt2.setFont(font)
        self.reduce_time_bt2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reduce_time_bt2.setStyleSheet("")
        self.reduce_time_bt2.setText("")
        self.reduce_time_bt2.setIcon(icon)
        self.reduce_time_bt2.setObjectName("reduce_time_bt2")
        self.horizontalLayout_21.addWidget(self.reduce_time_bt2)
        self.add_time_bt2 = QtWidgets.QPushButton(self.frame_28)
        self.add_time_bt2.setMinimumSize(QtCore.QSize(0, 30))
        self.add_time_bt2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.add_time_bt2.setFont(font)
        self.add_time_bt2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_time_bt2.setStyleSheet("")
        self.add_time_bt2.setText("")
        self.add_time_bt2.setIcon(icon1)
        self.add_time_bt2.setObjectName("add_time_bt2")
        self.horizontalLayout_21.addWidget(self.add_time_bt2)
        self.label_27 = QtWidgets.QLabel(self.frame_28)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_21.addWidget(self.label_27)
        self.verticalLayout_17.addWidget(self.frame_28)
        self.horizontalLayout_8.addWidget(self.frame_22)
        self.gridLayout.addWidget(self.widget_3, 0, 0, 1, 1)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.connect_functions()

        self.add_time_bt1.setDisabled(True)
        self.reduce_time_bt1.setDisabled(True)
        self.add_time_bt2.setDisabled(True)
        self.reduce_time_bt2.setDisabled(True)

        self.is_selected1 = False
        self.is_selected2 = False
        self.is_exclude1 = False
        self.is_exclude2 = False


    def connect_functions(self):
        self.exclude_stage1.stateChanged.connect(self.exclude_stage1_check)
        self.exclude_stage2.stateChanged.connect(self.exclude_stage2_check)
        self.wow_effects1.stateChanged.connect(self.wow_effects1_check)
        self.wow_effects2.stateChanged.connect(self.wow_effects2_check)
        self.check_stage1_time.stateChanged.connect(self.stage1_time_check)
        self.check_stage2_time.stateChanged.connect(self.stage2_time_check)
        self.add_time_bt1.pressed.connect(self.bt_add_time1_press)
        self.add_time_bt2.pressed.connect(self.bt_add_time2_press)
        self.reduce_time_bt1.pressed.connect(self.bt_reduce_time1_press)
        self.reduce_time_bt2.pressed.connect(self.bt_reduce_time2_press)
        self.start_stage1_button.pressed.connect(self.bt_start1_press)
        self.start_stage2_button.pressed.connect(self.bt_start2_press)
        self.stop_stage1_button.pressed.connect(self.bt_stop1_press)
        self.stop_stage2_button.pressed.connect(self.bt_stop2_press)


    def add_restart_button1(self):
        self.horizontalLayout_restart1.removeWidget(self.result_stage1_widget)
        self.result_stage1_widget = QtWidgets.QPushButton(text = '   Переиграть   ')
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_stage1_widget.sizePolicy().hasHeightForWidth())
        self.result_stage1_widget.setSizePolicy(sizePolicy)
        self.result_stage1_widget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.result_stage1_widget.setFont(font)
        self.result_stage1_widget.setStyleSheet("QPushButton{\n"
"    border-width: 3px;\n"
"    background-color: rgb(255, 255, 0);\n"
"    border-radius: 8px;\n"
"    padding: 10px"
"}"
"QPushButton:pressed\n"
"{\n"
"     background-color: #bbbb00;\n"
"}\n")
        self.result_stage1_widget.pressed.connect(self.bt_restart1_press)
        self.horizontalLayout_restart1.insertWidget(1, self.result_stage1_widget)

    def add_restart_button2(self):
        self.horizontalLayout_restart2.removeWidget(self.result_stage2_widget)
        self.result_stage2_widget = QtWidgets.QPushButton(text = '   Переиграть   ')
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_stage2_widget.sizePolicy().hasHeightForWidth())
        self.result_stage2_widget.setSizePolicy(sizePolicy)
        self.result_stage2_widget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.result_stage2_widget.setFont(font)
        self.result_stage2_widget.setStyleSheet("QPushButton{\n"
"    border-width: 3px;\n"
"    background-color: rgb(255, 255, 0);\n"
"    border-radius: 8px;\n"
"    padding: 10px"
"}"
"QPushButton:pressed\n"
"{\n"
"     background-color: #bbbb00;\n"
"}\n")
        self.result_stage2_widget.pressed.connect(self.bt_restart2_press)
        self.horizontalLayout_restart2.insertWidget(1, self.result_stage2_widget)

    def add_result_label1(self):
        self.horizontalLayout_restart1.removeWidget(self.result_stage1_widget)
        self.result_stage1_widget = QtWidgets.QLabel(text = '   Результат   ')
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_stage1_widget.sizePolicy().hasHeightForWidth())
        self.result_stage1_widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.result_stage1_widget.setFont(font)
        self.result_stage1_widget.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: white;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}")
        self.result_stage1_widget.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_restart1.insertWidget(1, self.result_stage1_widget)

    def add_result_label2(self):
        self.horizontalLayout_restart2.removeWidget(self.result_stage2_widget)
        self.result_stage2_widget = QtWidgets.QLabel(text = '   Результат   ')
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_stage2_widget.sizePolicy().hasHeightForWidth())
        self.result_stage2_widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.result_stage2_widget.setFont(font)
        self.result_stage2_widget.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: white;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}")
        self.result_stage2_widget.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_restart2.insertWidget(1, self.result_stage2_widget)

    def green_timer1(self):
        self.stage1_timer.setStyleSheet("QLabel\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #00bb00;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    color: #000000;\n"
"}")

    def red_timer1(self):
        self.stage1_timer.setStyleSheet("QLabel\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    color: #000000;\n"
"}")

    def green_timer2(self):
        self.stage2_timer.setStyleSheet("QLabel\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #00bb00;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    color: #000000;\n"
"}")

    def red_timer2(self):
        self.stage2_timer.setStyleSheet("QLabel\n"
"{\n"
"    border-style: solid;\n"
"    border-width: 3px;\n"
"    border-color:  #bb0000;\n"
"    background-color: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #B5B8B1, stop: 1 #ffffff);\n"
"    border-radius: 8px;\n"
"    color: #000000;\n"
"}")

    def wow_effects1_check(self):
        if self.is_selected1:
            if self.wow_effects1.checkState() == 2:
                settings.wowEffects = True
            else:
                settings.wowEffects = False

    def wow_effects2_check(self):
        if self.is_selected2:
            if self.wow_effects2.checkState() == 2:
                settings.wowEffects = True
            else:
                settings.wowEffects = False

    def exclude_stage1_check(self):
        if self.is_selected1:
            settings.excludeStageEvent = True
        elif self.is_exclude1:
            settings.includeStageEvent = True
        else:
            self.exclude_stage1.setCheckState(0)

    def exclude_stage2_check(self):
        if self.is_selected2:
            settings.excludeStageEvent = True
        elif self.is_exclude2:
            settings.includeStageEvent = True
        else:
            self.exclude_stage2.setCheckState(0)

    def exclude_stage1_event(self):
        self.is_selected1 = False
        self.is_exclude1 = True
        settings.currentStage = self.find_next()
        settings.changeStageEvent = True
        self.full_disabled_event1()
        self.gray_stage_label1()

    def exclude_stage2_event(self):
        self.is_selected2 = False
        self.is_exclude2 = True
        settings.currentStage = self.find_next()
        settings.changeStageEvent = True
        self.full_disabled_event2()
        self.gray_stage_label2()

    def include_stage1_event(self):
        self.is_selected1 = True
        self.is_exclude1 = False
        self.full_enabled_event1()
        self.white_stage_label1()
        self.find_previous()
        settings.changeStageEvent = True

    def include_stage2_event(self):
        self.is_selected2 = True
        self.is_exclude2 = False
        self.full_enabled_event2()
        self.white_stage_label2()
        self.find_previous()
        settings.changeStageEvent = True

    def exclude_disabling(self):
        if self.is_exclude1:
            self.is_exclude1 = False
            self.exclude_stage1.setDisabled(True)
        if self.is_exclude2:
            self.is_exclude2 = False
            self.exclude_stage2.setDisabled(True)

    def stage1_time_check(self):
        if self.is_selected1:
            if self.check_stage1_time.checkState() == 0:
                if not settings.stageStatus:
                    settings.stageTimer = 'increasing'
                self.stage1_timer.setText('00 : 00')
                self.add_time_bt1.setDisabled(True)
                self.reduce_time_bt1.setDisabled(True)
            else:
                if not settings.stageStatus:
                    settings.stageTimer = 'decreasing'
                self.set_time(settings.stageTime)
                self.add_time_bt1.setDisabled(False)
                self.reduce_time_bt1.setDisabled(False)

    def stage2_time_check(self):
        if self.is_selected2:
            if self.check_stage2_time.checkState() == 0:
                if not settings.stageStatus:
                    settings.stageTimer = 'increasing'
                self.stage2_timer.setText('00 : 00')
                self.add_time_bt2.setDisabled(True)
                self.reduce_time_bt2.setDisabled(True)
            else:
                if not settings.stageStatus:
                    settings.stageTimer = 'decreasing'
                self.set_time(settings.stageTime)
                self.add_time_bt2.setDisabled(False)
                self.reduce_time_bt2.setDisabled(False)

    def bt_add_time1_press(self):
        if self.is_selected1:
            if not settings.check_last():
                settings.stageTime+=60
                self.set_time(settings.stageTime)
            else:
                settings.mainTime+=60
                settings.addedTime+=60
                self.set_time(settings.mainTime)

    def bt_reduce_time1_press(self):
        if self.is_selected1:
            if not settings.check_last():
                if settings.stageTime > 60:
                    settings.stageTime-=60
                    self.set_time(settings.stageTime)
            else:
                if settings.addedTime and settings.mainTime-60 > 0:
                    settings.mainTime-=60
                    settings.addedTime-=60
                    self.set_time(settings.mainTime)

    def bt_add_time2_press(self):
        if self.is_selected2:
            if not settings.check_last():
                settings.stageTime+=60
                self.set_time(settings.stageTime)
            else:
                settings.mainTime+=60
                settings.addedTime+=60
                self.set_time(settings.mainTime)

    def bt_reduce_time2_press(self):
        if self.is_selected2:
            if not settings.check_last():
                if settings.stageTime > 60:
                    settings.stageTime-=60
                    self.set_time(settings.stageTime)
            else:
                if settings.addedTime and settings.mainTime-60 > 0:
                    settings.mainTime-=60
                    settings.addedTime-=60
                    self.set_time(settings.mainTime)

    def bt_start1_press(self):
        if self.is_selected1 and not settings.stageStatus:
            settings.startStageEvent = True

    def bt_start2_press(self):
        if self.is_selected2 and not settings.stageStatus:
            settings.startStageEvent = True

    def start_event(self):
        if self.is_selected1:
            self.wow_effects1_check()
            self.stage1_time_check()
            self.check_stage1_time.setDisabled(True)
            self.exclude_stage1.setDisabled(True)
            self.wow_effects1.setDisabled(True)
            self.green_timer1()
            self.green_stage_label1()
            self.green_start_button1()
        elif self.is_selected2:
            self.wow_effects2_check()
            self.stage2_time_check()
            self.check_stage2_time.setDisabled(True)
            self.exclude_stage2.setDisabled(True)
            self.wow_effects2.setDisabled(True)
            self.green_timer2()
            self.green_stage_label2()
            self.green_start_button2()

    def bt_stop1_press(self):
        if self.is_selected1 and settings.stageStatus:
            settings.stopStageEvent = True

    def bt_stop2_press(self):
        if self.is_selected2 and settings.stageStatus:
            settings.stopStageEvent = True

    def stop_event(self):
        if self.is_selected1:
            self.is_selected1 = False
            self.add_restart_button1()
            self.full_disabled_event1()
            self.red_timer1()
            self.gray_stage_label1()
            self.white_start_button1()
        elif self.is_selected2:
            self.is_selected2 = False
            self.add_restart_button2()
            self.full_disabled_event2()
            self.red_timer2()
            self.gray_stage_label2()
            self.white_start_button2()

    def full_disabled_event1(self):
        self.wow_effects1.setDisabled(True)
        self.start_stage1_button.setDisabled(True)
        self.stop_stage1_button.setDisabled(True)
        self.check_stage1_time.setDisabled(True)
        self.add_time_bt1.setDisabled(True)
        self.reduce_time_bt1.setDisabled(True)

    def full_disabled_event2(self):
        self.wow_effects2.setDisabled(True)
        self.start_stage2_button.setDisabled(True)
        self.stop_stage2_button.setDisabled(True)
        self.check_stage2_time.setDisabled(True)
        self.add_time_bt2.setDisabled(True)
        self.reduce_time_bt2.setDisabled(True)

    def full_enabled_event1(self):
        self.wow_effects1.setDisabled(False)
        self.start_stage1_button.setDisabled(False)
        self.stop_stage1_button.setDisabled(False)
        self.check_stage1_time.setDisabled(False)
        self.add_time_bt1.setDisabled(False)
        self.reduce_time_bt1.setDisabled(False)

    def full_enabled_event2(self):
        self.wow_effects2.setDisabled(False)
        self.start_stage2_button.setDisabled(False)
        self.stop_stage2_button.setDisabled(False)
        self.check_stage2_time.setDisabled(False)
        self.add_time_bt2.setDisabled(False)
        self.reduce_time_bt2.setDisabled(False)

    def find_next(self):
        settings.stages[settings.currentStage-1] = False
        i = 0
        for stage in settings.stages:
            i+=1
            if stage:
                return i
        return 0

    def find_previous(self):
        settings.currentStage = settings.currentStage-1
        settings.stages[settings.currentStage-1] = True

    def bt_restart1_press(self):
        if not settings.stageStatus:
            self.is_selected1 = True
            settings.restartStageEvent = True
            self.add_result_label1()
            self.full_enabled_event1()
            self.stage1_time_check()

    def bt_restart2_press(self):
        if not settings.stageStatus:
            self.is_selected2 = True
            settings.restartStageEvent = True
            self.add_result_label2()
            self.full_enabled_event2()
            self.stage2_time_check()

    def set_time(self, time):
        if time < 3600:
            if self.is_selected1:
                self.stage1_timer.setText(
                    f"{settings.get_minutes(time)} :" +\
                    f" {settings.get_seconds(time)}")
            elif self.is_selected2:
                self.stage2_timer.setText(
                    f"{settings.get_minutes(time)} :" +\
                    f" {settings.get_seconds(time)}")
        else:
            if self.is_selected1:
                self.stage1_timer.setText(
                    f"{settings.get_hours(time)} :" +\
                    f"{settings.get_minutes(time)} :" +\
                    f" {settings.get_seconds(time)}")
            elif self.is_selected2:
                self.stage2_timer.setText(
                    f"{settings.get_hours(time)} :" +\
                    f"{settings.get_minutes(time)} :" +\
                    f" {settings.get_seconds(time)}")

    def init_time(self):
        if settings.stageTimer == 'increasing':
            settings.stageTime = 0
        else:
            pass

    def yellow_stage_label1(self):
        self.stage_label1.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: #ffff00;\n"
"    color: #ffff00;\n"
"    border-radius: 8px;\n"
"}")

    def green_stage_label1(self):
        self.stage_label1.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: #00ff00;\n"
"    color: #00ff00;\n"
"    border-radius: 8px;\n"
"}")

    def gray_stage_label1(self):
        self.stage_label1.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: #cfd1cd;\n"
"    color: #cfd1cd;\n"
"    border-radius: 8px;\n"
"}")

    def white_stage_label1(self):
        self.stage_label1.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: #ffffff;\n"
"    color: #ffffff;\n"
"    border-radius: 8px;\n"
"}")

    def yellow_stage_label2(self):
        self.stage_label2.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: #ffff00;\n"
"    color: #ffff00;\n"
"    border-radius: 8px;\n"
"}")

    def green_stage_label2(self):
        self.stage_label2.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: #00ff00;\n"
"    color: #00ff00;\n"
"    border-radius: 8px;\n"
"}")

    def gray_stage_label2(self):
        self.stage_label2.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: #cfd1cd;\n"
"    color: #cfd1cd;\n"
"    border-radius: 8px;\n"
"}")

    def white_stage_label2(self):
        self.stage_label2.setStyleSheet("QLabel{\n"
"    border-style: dashed;\n"
"    border-width: 3px;\n"
"    border-color: #cfd1cd;\n"
"    color: #cfd1cd;\n"
"    border-radius: 8px;\n"
"}")

    def green_start_button1(self):
        self.start_stage1_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #00ff00;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #00bb00;\n"
"}")

    def green_start_button2(self):
        self.start_stage2_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #00ff00;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #00bb00;\n"
"}")

    def white_start_button1(self):
        self.start_stage1_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #ffffff;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #cfd1cd;\n"
"}")

    def white_start_button2(self):
        self.start_stage2_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #ffffff;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"     background-color: #cfd1cd;\n"
"}")

    def last_stage_event(self):
        self.exclude_stage2.setDisabled(True)
        self.check_stage2_time.setCheckState(2)
        self.check_stage2_time.setDisabled(True)
        self.add_time_bt2.setDisabled(False)
        self.reduce_time_bt2.setDisabled(False)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.stage_label1.setText(_translate("Form", "Подэтап 1"))
        self.exclude_stage1.setText(_translate("Form", "Исключить"))
        self.wow_effects1.setText(_translate("Form", "WOW-эффекты"))
        self.start_stage1_button.setText(_translate("Form", "Запуск"))
        self.stop_stage1_button.setText(_translate("Form", "Стоп"))
        self.result_stage1_widget.setText(_translate("Form", "   Результат   "))
        self.label_20.setText(_translate("Form", "Примечание: "))
        self.check_stage1_time.setText(_translate("Form", "Время"))
        self.stage1_timer.setText(_translate("Form", "00 : 00"))
        self.label_22.setText(_translate("Form", "-1 мин"))
        self.label_23.setText(_translate("Form", "+1 мин"))
        self.stage_label2.setText(_translate("Form", "Подэтап 2"))
        self.exclude_stage2.setText(_translate("Form", "Исключить"))
        self.wow_effects2.setText(_translate("Form", "WOW-эффекты"))
        self.start_stage2_button.setText(_translate("Form", "Запуск"))
        self.stop_stage2_button.setText(_translate("Form", "Стоп"))
        self.result_stage2_widget.setText(_translate("Form", "   Результат   "))
        self.label_24.setText(_translate("Form", "Примечание: "))
        self.check_stage2_time.setText(_translate("Form", "Время"))
        self.stage2_timer.setText(_translate("Form", "00 : 00"))
        self.label_26.setText(_translate("Form", "-1 мин"))
        self.label_27.setText(_translate("Form", "+1 мин"))
